@baseUrl = http://localhost:5000
@urlPath = api/v1

### 
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "kimsson",
  "password": "ytrewq",
  "email": "identity@kimsson.com",
  "avatarColor": "hotpink",
  "avatarImage": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVQYV2NgYAAAAAMAAWgmWQ0AAAAASUVORK5CYII="
}

### 
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "kimsson",
  "password": "ytrewq"
}

### 
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

### 
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true

### 
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "email": "identity@kimsson.com"
}

### 
POST {{baseUrl}}/{{urlPath}}/reset-password/39873611d025e85a3d99886b25ae91bcc6710ab9
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "password": "ytrewq",
    "confirmPassword": "ytrewq"
}
